class NotFoundUserBasicException(Exception): ...


class UserAlreadyExistsBasicException(Exception): ...


class UserWithThisEmailAlreadyExistsBasicException(Exception): ...


class UserWithThisUsernameAlreadyExistsBasicException(Exception): ...
